# TODO: Create a “DummySite” resource that takes has a string property called “website_url”.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dummysites.stable.dwk
spec:
  group: stable.dwk
  scope: Namespaced
  names:
    kind: DummySite
    plural: dummysites
    singular: dummysite
    shortNames:
      # ds = DaemonSets!!!
      - dmmyst
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                website_url:
                  type: string
                successful:
                  type: boolean
                html:
                  type: string
                path_in_pod:
                  type: string
      additionalPrinterColumns:
        - name: WebsiteUrl
          type: string
          description: URL of a Website
          jsonPath: .spec.website_url
          priority: 0
        - name: Successful
          type: boolean
          description: Status after scrape
          jsonPath: .spec.successful
          priority: 0
        - name: HTML
          type: string
          description: HTML of Website
          jsonPath: .spec.html
          priority: 1
        - name: PathInPod
          type: string
          description: Path to Dump in Controller Pod
          jsonPath: .spec.path_in_pod
          priority: 0
