apiVersion: v1
kind: Secret
metadata:
  namespace: project
  name: postgres-pw-url
data:
  # app just needs a postgres url postgresql://postgres:passw0rd@postgres-project-svc:5432/postgres
  POSTGRES_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3MHJkQHBvc3RncmVzLXByb2plY3Qtc3ZjOjU0MzIvcG9zdGdyZXM=
  # db setup requires the passw0rd the rest stays default (user/db: 'postgres')
  POSTGRES_PASSWORD: cGFzc3cwcmQ=
