apiVersion: v1
kind: Secret
metadata:
  namespace: project
  name: postgres-pw-url
data:
  PGDATABASE: cG9zdGdyZXM=
  PGHOST: cG9zdGdyZXMtcHJvamVjdC1zdmM=
  PGPASSWORD: cGFzc3cwcmQ=
  PGPORT: NTQzMg==
  PGUSER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cGFzc3cwcmQ=
  POSTGRES_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3MHJkQHBvc3RncmVzLXByb2plY3Qtc3ZjOjU0MzIvcG9zdGdyZXM=