apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: "2020-09-03T14:59:34Z"
  name: telegram-secret
  namespace: project
data:
  # of course access_token and chat_id need to set to real values
  # nats://my-nats:4222
  NATS_URL: bmF0czovL215LW5hdHM6NDIyMg==
  # 123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11
  TELEGRAM_ACCESS_TOKEN: MTIzNDU2OkFCQy1ERUYxMjM0Z2hJa2wtenl4NTdXMnYxdTEyM2V3MTE=
  # -123456789
  TELEGRAM_CHAT_ID: LTEyMzQ1Njc4OQ==
